CREATE DATABASE IF NOT EXISTS descarteResiduo;

USE descarteResiduo;

CREATE TABLE IF NOT EXISTS pontos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255),
    endereco VARCHAR(255),
    zona VARCHAR(100),
    contatos VARCHAR(255),
    horario_expediente VARCHAR(255)
);

INSERT INTO pontos (nome, endereco, zona, contatos, horario_expediente) VALUES
('Pão de Açúcar - Guatás', 'Al. Dos Guatás, 1261 - Vila da Saúde - São Paulo - SP, 04053-042', 'Sul', NULL, NULL),
('Pão de Açúcar - Maracatins', 'Al. Dos Maracatins, 1545 - Indianópolis - São Paulo - SP, 04089-015', 'Sul', NULL, NULL),
('Pão de Açúcar - Jardim Paulistano', 'Al. Gabriel Monteiro da Silva, 1351 - Jardim America - São Paulo - SP, 01441-002', 'Oeste', NULL, NULL),
('Assaí Aguia De Haia', 'Av. Aguia de Haia, 2636 - Parque Paineiras - São Paulo - SP, 03694-000', 'Leste', NULL, NULL),
('PEV - AME Barradas', 'Av. Almirante Delamare, 1534 - Cidade Nova Heliópolis - São Paulo - SP, 04230-000', 'Sul', NULL, NULL),
('Carrefour - Penha', 'Av. Amador Bueno da Veiga, 2521 - Penha De França - São Paulo - SP, 03653-000', 'Leste', NULL, NULL),
('Colégio Santa Cruz', 'Av. Arruda Botelho, 255 - Alto de Pinheiros - São Paulo - SP, 05466-000', 'Oeste', NULL, NULL),
('Tenda Atlântica', 'Av. Atlântica, 1000 - Socorro - São Paulo - SP', 'Sul', NULL, NULL),
('UBS Vila Ramos - Dr. Luiz Augusto de Campos', 'Av. Augusto Antunes, 1631 - Limoeiro - São Paulo - SP, 08235-630', 'Leste', NULL, NULL),
('Pão de Açúcar - Jardim Paulista', 'Av. Brigadeiro Luís Antônio, 3126 - Jardim Paulista - São Paulo - SP, 01402-000', 'Oeste', NULL, NULL),
('Viação Campo Belo Ltda II', 'Av. Carlos Lacerda, 2551 - Jardim Rosana - São Paulo - SP, 05789-001', 'Sul', NULL, NULL),
('UBS Jardim Valquiria', 'Av. Carlos Lacerda, 3093 - Vila Pirajussara - São Paulo - SP, 05789-001', 'Sul', NULL, NULL),
('UBS Jardim Sao Carlos', 'Av. César Augusto Romaro, 500 - Vila Norma - São Paulo - SP, 08062-000', 'Leste', NULL, NULL),
('UBS Jardim Rosinha', 'Av. Dalva de Oliveira, 82 - Jardim Rosinha - São Paulo - SP, 05274-001', 'Norte', NULL, NULL),
('SASF - Dom Mario Gurgel', 'Av. Direitos Humanos, 701 - Imirim - São Paulo - SP, 02475-000', 'Norte', NULL, NULL),
('Coopere Centro', 'Av. do Estado - Bom Retiro - São Paulo - SP, 01107-000', 'Centro', NULL, NULL),
('UBS Parque Engenho II', 'Av. Dom Rodrigo Sanches, 700 - Pq Engenho - São Paulo - SP, 05892-360', 'Sul', NULL, NULL),
('UBS Vera Cruz - Dr Fernando Proenca de Gouvea', 'Av. dos Funcionários Públicos, 379 - Vila do Sol - São Paulo - SP, 04962-000', 'Sul', NULL, NULL),
('UBS Jardim Santa Terezinha', 'Av. dos Latinos, 205 - Jardim Santa Teresinha - São Paulo - SP, 03572-000', 'Leste', NULL, NULL),
('Pão de Açúcar - Vila Clementino', 'Av. Dr. Altino Arantes, 268 - Vila Clementino - São Paulo - SP, 04042-001', 'Sul', NULL, NULL),
('Parque Barragem Guarapiranga', 'Av. Dr. Caetano Petralia Sobrinho, 43 - Jardim Guarapiranga - São Paulo - SP, 04770-020', 'Sul', NULL, NULL),
('Carrefour - Morumbi', 'Av. Dr. Guilherme Dumont Vilares, 1015 - Vila Suzana - São Paulo - SP, 05640-001', 'Oeste', NULL, NULL),
('G&V Primos Gás Comércio Ltda', 'Av. Edu Chaves, 942 - Parque Edu Chaves - São Paulo - SP, 02229-000', 'Norte', NULL, NULL),
('Pão de Açúcar - Jabaquara', 'Av. Eng. Armando de Arruda Pereira, 1827 - Jabaquara - São Paulo - SP, 04309-011', 'Sul', NULL, NULL),
('Assaí Casa Verde', 'Av. Eng. Caetano Alvares, 1927 - Limão - São Paulo - SP, 02546-000', 'Norte', NULL, NULL),
('Still Vox Eletrônica Barão', 'Al. Barão de Limeira, 1180 - Campos Elíseos - São Paulo - SP, 01202-002', 'Centro', NULL, NULL),
('Sesc Unidade Bom Retiro', 'Al. Nothmann, 42 - Campos Elíseos - São Paulo - SP, 01216-000', 'Centro', NULL, NULL),
('Parque do Carmo', 'Av. Afonso de Sampaio e Sousa, 951 - Itaquera - São Paulo - SP, 08275-025', 'Leste', NULL, NULL),
('Sesc Administração Central', 'Av. Alvaro Ramos, 991 - Belenzinho - São Paulo - SP', 'Leste', NULL, NULL),
('Atacadão - Aricanduva', 'Av. Aricanduva, 3640 - Gleba do Pêssego - São Paulo - SP, 03930-110', 'Leste', NULL, NULL),
('Assaí - Aricanduva', 'Av. Aricanduva, 5555 - Jd. Santa Terezinha - São Paulo - SP, 03527-000', 'Leste', NULL, NULL),
('MATRIZ – Galpão Sucata Digital', 'Rua Templários, 192, Vila Formosa', 'Zona Leste', '(11) 95768-2368', 'Segunda à Quinta das 08h às 18h, Sexta das 08h às 17h'),
('ICRR CELL Assistência (Loja 1)', 'Avenida Líder, 2810, Cidade Líder', 'Zona Leste', '(11) 97389-5065', 'Segunda à Sexta das 09h às 17h'),
('ETEC Professor Adhemar Batista Heméritas', 'Rua Abilene, 16, Parque Santo Antônio', 'Zona Sul', '(11) 99596-0077', 'Segunda à Sexta das 07h às 23h'),
('SENAC Tatuapé', 'Rua Coronel Luiz Americano, 130, Tatuapé', 'Zona Leste', '(11) 99347-9348', 'Segunda à Sexta das 09h às 17h'),
('GoodStorage – Unidade Tatuapé', 'Av. Celso Garcia, 4638, Tatuapé', 'Zona Leste', '(11) 3340-4663', 'Segunda à Sexta das 07h às 19h'),
('Amplifique Coworking', 'R. Tabajaras, 439 – Mooca', 'Zona Leste', '(11) 4200-0880', 'Segunda à Sexta das 08h às 18h'),
('Crystal Tower', 'Rua Lydia Ferrari Magnoli, 108, Jardim Avelino', 'Zona Sudeste', '(11) 2345-7860', 'Segunda à Sexta das 09h às 17h'),
('Shopping Pátio Paulista', 'Rua Treze de Maio, 1947 – 4º Pavimento, Bela Vista', 'Centro', '(11) 3179-8504', 'Segunda à Segunda das 10h às 20h'),
('GoodStorage (Unidade Estado)', 'Av. Do Estado, 5460, Cambuci', 'Centro', '(11) 3340-4663', 'Segunda a Sexta das 07h às 19h'),
('UNIMED', 'R. José Getúlio, 78/90, Aclimação', 'Centro', '(11) 2146-2603', 'Segunda à Sexta das 09h às 17h'),
('GoodStorage (Unidade Lapa)', 'Av. Embargador Macedo Soares, 977, Parque Res. da Lapa', 'Zona Oeste', '(11) 2348-4663', 'Segunda à Sexta das 07h às 19h'),
('GoodStorage (Unidade Jaguaré)', 'Av. Gonçalo Madeira, 220, Jaguaré', 'Zona Oeste', '(11) 4095-6558', 'Segunda à Sexta das 07h às 19h'),
('Condomínio Villa Lobos Office Park', 'Avenida Queiroz Filho, 1700, Vila Hamburguesa', 'Zona Oeste', '(11) 4302-5842', 'Atendimento 24 horas'),
('AGS4 Office Coworking', 'Rua Professor Ernest Marcus, 65, Pacaembu', 'Zona Oeste', '(11) 3231-5550', 'Segunda à Sexta das 09h às 19h'),
('GoodStorage (Unidade Morumbi)', 'Av Giovanni Gronchi, 5400, Vila Andrade', 'Zona Oeste', '(11) 3054-4663', 'Segunda à Sexta das 07h às 19h'),
('Parque Luis Carlos Prestes', 'Rua João Della Manna, 665, JD ROLINOPOLIS', 'Zona Oeste', '(11) 95220-0443', 'Segunda à Sexta das 08h às 17h'),
('Condomínio Vista Verde Offices', 'Av. Queiroz Filho, 1560, Vila Andrade', 'Zona Oeste', '(11) 94024-4333', 'Segunda à Sexta das 08h às 20h'),
('Morumbi Town Shopping', 'Av. Giovanni Gronchi, 5930, Vila Andrade', 'Zona Oeste', '(11) 3740-6946', 'Segunda à Sábado das 10h às 22h, Domingos e Feriados das 14h às 20h'),
('Instituto Madre Mazzarello', 'R. Praça Domingos Correia da Cruz, 14, Santana', 'Zona Norte', '(11) 94016-0954', 'Segunda à Sexta das 07h às 17h'),
('CEU PERUS', 'R. Bernardo José de Lorena s/n, Vila Fanton', 'Zona Norte', '(11) 3915-8751', 'Segunda à domingo das 07h às 22h'),
('EDIFÍCIO LUIZ FRANCO', 'Rua Felício Marcondes, nº 436, Centro, Guarulhos', 'Região Metropolitana', NULL, 'Segunda à sexta das 08h às 20h, Sábado das 09h às 13h'),
('Shopping Internacional De Guarulhos', 'Rua Engenheiro Camilo Olivetti, 295, Vila Itapegica, Guarulhos', 'Região Metropolitana', '(11) 2345-7860', 'Segunda à sábado das 10h às 22h, Domingo das 11h às 18h'),
('SENAC – Taboão da Serra', 'Rua Salvador Branco de Andrade, 182, Jardim São Miguel, Taboão da Serra', 'Região Metropolitana', '(11) 98687-0059', 'Segunda à Sexta das 09h às 17h'),
('Grupo Bertoni – Ultragaz – Franco da Rocha', 'Av. da Saudade, 1091, Monte Verde', 'Região Metropolitana', '(11) 97508-4116', 'Segunda à Segunda das 08h às 18h'),
('TECSI Automação Industrial – ABC', 'Rua Francisco Ôngaro, 56, São Bernardo do Campo', 'Região Metropolitana', '(11) 93535-1047', 'Segunda à Sexta das 08h às 18h'),
('EMEB Natalina Cuzziol Ferro – ABC', 'Rua Salim Mafhoud, 965, Terra Nova II, São Bernardo do Campo – SP', 'Região Metropolitana', '(11) 93489-0984', 'Segunda à sexta das 09h às 17h'),
('UBS Luiz Ernesto Mazzoni', 'Av. Carlos Liviero, 566 - Vila Liviero - São Paulo - SP, 04186-100', 'Sul', NULL, NULL),
('Sodimac Dicico - Tremembé', 'Av. Cel. Sezefredo Fagundes, 1855 - Tucuruvi - São Paulo - SP, 02306-000', 'Norte', NULL, NULL),
('Panafax Videoeletronica', 'Av. Celso Garcia, 2874 - Tatuapé - São Paulo - SP, 03064-100', 'Leste', NULL, NULL),
('Assaí Vila Moreira', 'Av. Condessa Elisabeth de Robiano, 2176 - Vila Moreira - São Paulo - SP', 'Leste', NULL, NULL),
('Assaí Jardim América da Penha', 'Av. Condessa Elisabeth de Robiano, 5500 - Jardim América Da Penha - São Paulo - SP, 03704-900', 'Leste', NULL, NULL),
('Casas Bahia - Vila Carrão', 'Av. Conselheiro Carrão, 2260 - Vila Carrao - São Paulo - SP, 03402-002', 'Leste', NULL, NULL),
('Com e Ass Tec Eletd Carrao', 'Av. Conselheiro Carrão, 3134 - Vila Carrão - São Paulo - SP, 03402-003', 'Leste', NULL, NULL),
('EHSC Comércio de Utilidades', 'Av. da Aclimação, 734 - Aclimação - São Paulo - SP, 01532-001', 'Centro', NULL, NULL),
('Suguiura Materiais para Construção', 'Av. da Barreira Grande, 2903 - Vila Bancária - São Paulo - SP, 03916-000', 'Leste', NULL, NULL),
('Compre Bem - Imperador', 'Av. do Imperador, 5000 - São Miguel Paulista - São Paulo - SP, 08050-000', 'Leste', NULL, NULL),
('Casas Bahia - Parque São Lucas', 'Av. do Oratório, 2265 - Vila Paulo Silas - São Paulo - SP, 03221-100', 'Leste', NULL, NULL),
('Parque Chuvisco', 'Av. dos Estados, 7430 - Parque Central - São Paulo - SP, 09220-570', 'ABC', NULL, NULL),
('Suguiura Materiais para Construção', 'Av. Doutor Bernardino Brito Fonseca de Carvalho, 2203 - Vila Matilde - São Paulo - SP, 03557-080', 'Leste', NULL, NULL),
('Casas Bahia - Jardim Oliveiras', 'Av. Dr. Almiro Leal da Costa, 370 - Jardim das Oliveiras - São Paulo - SP, 08122-260', 'Leste', NULL, NULL),
('Atacadão - Jacuí', 'Av. Dr. Custódio de Lima, 297 - Parque Cruzeiro do Sul - São Paulo - SP, 08071-000', 'Leste', NULL, NULL);